# Verilog Emission
# Final emission of Verilog files from RTL module

"""
    emit_verilog(rtl::RTLModule)

Emit complete Verilog module as a string.
"""
function emit_verilog(rtl::RTLModule)::String
    lines = String[]

    # File header
    push!(lines, "//============================================================")
    push!(lines, "// Generated by FPGACompiler.jl")
    push!(lines, "// Module: $(rtl.name)")
    push!(lines, "// Generated: $(Dates.format(Dates.now(), "yyyy-mm-dd HH:MM:SS"))")
    push!(lines, "//============================================================")
    push!(lines, "")

    # Timescale
    push!(lines, "`timescale 1ns / 1ps")
    push!(lines, "")

    # Module declaration
    push!(lines, "module $(rtl.name) (")
    push!(lines, rtl.port_declarations)
    push!(lines, ");")
    push!(lines, "")

    # Parameters (state encoding)
    if !isempty(rtl.parameter_declarations)
        push!(lines, "    // State encoding")
        push!(lines, rtl.parameter_declarations)
        push!(lines, "")
    end

    # Signal declarations
    if !isempty(rtl.signal_declarations)
        push!(lines, "    // Internal signals")
        push!(lines, rtl.signal_declarations)
        push!(lines, "")
    end

    # FSM logic
    if !isempty(rtl.fsm_logic)
        push!(lines, rtl.fsm_logic)
        push!(lines, "")
    end

    # Datapath logic
    if !isempty(rtl.datapath_logic)
        push!(lines, rtl.datapath_logic)
        push!(lines, "")
    end

    # Memory logic
    if !isempty(rtl.memory_logic)
        push!(lines, rtl.memory_logic)
        push!(lines, "")
    end

    # Output logic
    if !isempty(rtl.output_logic)
        push!(lines, rtl.output_logic)
        push!(lines, "")
    end

    # Module end
    push!(lines, "endmodule")
    push!(lines, "")

    return join(lines, "\n")
end

"""
    write_verilog(rtl::RTLModule, filepath::String)

Write Verilog module to a file.
"""
function write_verilog(rtl::RTLModule, filepath::String)
    verilog_code = emit_verilog(rtl)
    open(filepath, "w") do f
        write(f, verilog_code)
    end
    return filepath
end

"""
    emit_testbench(rtl::RTLModule; num_test_vectors::Int=10)

Generate a basic Verilog testbench for the module.
"""
function emit_testbench(rtl::RTLModule; num_test_vectors::Int=10)::String
    lines = String[]

    module_name = rtl.name

    # File header
    push!(lines, "//============================================================")
    push!(lines, "// Testbench for $(module_name)")
    push!(lines, "// Generated by FPGACompiler.jl")
    push!(lines, "//============================================================")
    push!(lines, "")

    push!(lines, "`timescale 1ns / 1ps")
    push!(lines, "")

    push!(lines, "module $(module_name)_tb;")
    push!(lines, "")

    # Clock and reset
    push!(lines, "    // Clock and reset")
    push!(lines, "    reg clk;")
    push!(lines, "    reg rst;")
    push!(lines, "")

    # Clock period
    push!(lines, "    // Clock period")
    push!(lines, "    parameter CLK_PERIOD = 10;")
    push!(lines, "")

    # Declare signals for DUT connections
    push!(lines, "    // DUT signals")
    for port in rtl.ports
        if port.name in ("clk", "rst")
            continue  # Already declared
        end

        dir = port.is_input ? "reg" : "wire"
        signed_str = port.is_signed ? "signed " : ""

        if port.bit_width == 1
            push!(lines, "    $dir $(signed_str)$(port.name);")
        else
            push!(lines, "    $dir $(signed_str)[$(port.bit_width-1):0] $(port.name);")
        end
    end
    push!(lines, "")

    # DUT instantiation
    push!(lines, "    // DUT instantiation")
    push!(lines, "    $module_name dut (")

    port_connections = String[]
    for port in rtl.ports
        push!(port_connections, "        .$(port.name)($(port.name))")
    end
    push!(lines, join(port_connections, ",\n"))

    push!(lines, "    );")
    push!(lines, "")

    # Clock generation
    push!(lines, "    // Clock generation")
    push!(lines, "    initial begin")
    push!(lines, "        clk = 0;")
    push!(lines, "        forever #(CLK_PERIOD/2) clk = ~clk;")
    push!(lines, "    end")
    push!(lines, "")

    # Reset and test sequence
    push!(lines, "    // Test sequence")
    push!(lines, "    initial begin")
    push!(lines, "        // Initialize signals")
    push!(lines, "        rst = 1;")
    push!(lines, "        start = 0;")

    # Initialize input ports
    for port in rtl.ports
        if port.is_input && !(port.name in ("clk", "rst", "start"))
            push!(lines, "        $(port.name) = 0;")
        end
    end
    push!(lines, "")

    push!(lines, "        // Wait for reset")
    push!(lines, "        #(CLK_PERIOD * 5);")
    push!(lines, "        rst = 0;")
    push!(lines, "        #(CLK_PERIOD * 2);")
    push!(lines, "")

    # Test vectors
    push!(lines, "        // Test vector 1")
    for port in rtl.ports
        if port.is_input && !(port.name in ("clk", "rst", "start"))
            push!(lines, "        $(port.name) = $(port.bit_width)'d1;")
        end
    end
    push!(lines, "        start = 1;")
    push!(lines, "        #CLK_PERIOD;")
    push!(lines, "        start = 0;")
    push!(lines, "")

    push!(lines, "        // Wait for done")
    push!(lines, "        wait(done);")
    push!(lines, "        #CLK_PERIOD;")
    push!(lines, "")

    # Check outputs
    push!(lines, "        // Display results")
    push!(lines, "        \$display(\"Test completed\");")
    for port in rtl.ports
        if !port.is_input
            push!(lines, "        \$display(\"$(port.name) = %d\", $(port.name));")
        end
    end
    push!(lines, "")

    push!(lines, "        #(CLK_PERIOD * 10);")
    push!(lines, "        \$finish;")
    push!(lines, "    end")
    push!(lines, "")

    # Waveform dump
    push!(lines, "    // Waveform dump")
    push!(lines, "    initial begin")
    push!(lines, "        \$dumpfile(\"$(module_name)_tb.vcd\");")
    push!(lines, "        \$dumpvars(0, $(module_name)_tb);")
    push!(lines, "    end")
    push!(lines, "")

    push!(lines, "endmodule")
    push!(lines, "")

    return join(lines, "\n")
end

"""
    write_testbench(rtl::RTLModule, filepath::String; kwargs...)

Write testbench to a file.
"""
function write_testbench(rtl::RTLModule, filepath::String; kwargs...)
    tb_code = emit_testbench(rtl; kwargs...)
    open(filepath, "w") do f
        write(f, tb_code)
    end
    return filepath
end

"""
    emit_cocotb_testbench(rtl::RTLModule)

Generate a cocotb Python testbench.
"""
function emit_cocotb_testbench(rtl::RTLModule)::String
    lines = String[]

    module_name = rtl.name

    push!(lines, "\"\"\"")
    push!(lines, "Cocotb testbench for $(module_name)")
    push!(lines, "Generated by FPGACompiler.jl")
    push!(lines, "\"\"\"")
    push!(lines, "")

    push!(lines, "import cocotb")
    push!(lines, "from cocotb.clock import Clock")
    push!(lines, "from cocotb.triggers import RisingEdge, FallingEdge, Timer, ClockCycles")
    push!(lines, "")

    push!(lines, "@cocotb.test()")
    push!(lines, "async def test_basic(dut):")
    push!(lines, "    \"\"\"Basic test for $(module_name)\"\"\"")
    push!(lines, "")
    push!(lines, "    # Start clock")
    push!(lines, "    clock = Clock(dut.clk, 10, units=\"ns\")")
    push!(lines, "    cocotb.start_soon(clock.start())")
    push!(lines, "")
    push!(lines, "    # Reset")
    push!(lines, "    dut.rst.value = 1")
    push!(lines, "    dut.start.value = 0")

    # Initialize inputs
    for port in rtl.ports
        if port.is_input && !(port.name in ("clk", "rst", "start"))
            push!(lines, "    dut.$(port.name).value = 0")
        end
    end
    push!(lines, "")

    push!(lines, "    await ClockCycles(dut.clk, 5)")
    push!(lines, "    dut.rst.value = 0")
    push!(lines, "    await ClockCycles(dut.clk, 2)")
    push!(lines, "")

    push!(lines, "    # Set inputs")
    for port in rtl.ports
        if port.is_input && !(port.name in ("clk", "rst", "start"))
            push!(lines, "    dut.$(port.name).value = 1")
        end
    end
    push!(lines, "")

    push!(lines, "    # Start operation")
    push!(lines, "    dut.start.value = 1")
    push!(lines, "    await RisingEdge(dut.clk)")
    push!(lines, "    dut.start.value = 0")
    push!(lines, "")

    push!(lines, "    # Wait for done")
    push!(lines, "    while dut.done.value != 1:")
    push!(lines, "        await RisingEdge(dut.clk)")
    push!(lines, "")

    push!(lines, "    # Check results")
    push!(lines, "    print(f\"Operation completed\")")
    for port in rtl.ports
        if !port.is_input && port.name != "done"
            push!(lines, "    print(f\"$(port.name) = {dut.$(port.name).value}\")")
        end
    end
    push!(lines, "")

    push!(lines, "    await ClockCycles(dut.clk, 5)")
    push!(lines, "")

    return join(lines, "\n")
end

"""
    emit_makefile(rtl::RTLModule; simulator::Symbol=:verilator)

Generate a Makefile for simulation.
"""
function emit_makefile(rtl::RTLModule; simulator::Symbol=:verilator)::String
    lines = String[]
    module_name = rtl.name

    push!(lines, "# Makefile for $(module_name)")
    push!(lines, "# Generated by FPGACompiler.jl")
    push!(lines, "")

    push!(lines, "MODULE = $(module_name)")
    push!(lines, "VERILOG_SOURCES = \$(MODULE).v")
    push!(lines, "TESTBENCH = \$(MODULE)_tb.v")
    push!(lines, "")

    if simulator == :verilator
        push!(lines, "# Verilator simulation")
        push!(lines, "VERILATOR = verilator")
        push!(lines, "VERILATOR_FLAGS = --cc --exe --build -j 0 --trace")
        push!(lines, "")
        push!(lines, "all: sim")
        push!(lines, "")
        push!(lines, "sim: \$(VERILOG_SOURCES)")
        push!(lines, "\t\$(VERILATOR) \$(VERILATOR_FLAGS) \$(VERILOG_SOURCES) sim_main.cpp")
        push!(lines, "\t./obj_dir/V\$(MODULE)")
        push!(lines, "")
        push!(lines, "lint: \$(VERILOG_SOURCES)")
        push!(lines, "\t\$(VERILATOR) --lint-only \$(VERILOG_SOURCES)")
        push!(lines, "")
    elseif simulator == :iverilog
        push!(lines, "# Icarus Verilog simulation")
        push!(lines, "IVERILOG = iverilog")
        push!(lines, "VVP = vvp")
        push!(lines, "")
        push!(lines, "all: sim")
        push!(lines, "")
        push!(lines, "\$(MODULE).vvp: \$(VERILOG_SOURCES) \$(TESTBENCH)")
        push!(lines, "\t\$(IVERILOG) -o \$@ \$^")
        push!(lines, "")
        push!(lines, "sim: \$(MODULE).vvp")
        push!(lines, "\t\$(VVP) \$<")
        push!(lines, "")
        push!(lines, "waves: \$(MODULE)_tb.vcd")
        push!(lines, "\tgtkwave \$<")
        push!(lines, "")
    end

    push!(lines, "clean:")
    push!(lines, "\trm -rf obj_dir *.vcd *.vvp")
    push!(lines, "")
    push!(lines, ".PHONY: all sim clean lint waves")
    push!(lines, "")

    return join(lines, "\n")
end

"""
    emit_verilator_main(rtl::RTLModule)

Generate Verilator C++ main file for simulation.
"""
function emit_verilator_main(rtl::RTLModule)::String
    lines = String[]
    module_name = rtl.name

    push!(lines, "// Verilator simulation main")
    push!(lines, "// Generated by FPGACompiler.jl")
    push!(lines, "")

    push!(lines, "#include <verilated.h>")
    push!(lines, "#include <verilated_vcd_c.h>")
    push!(lines, "#include \"V$(module_name).h\"")
    push!(lines, "")

    push!(lines, "#include <iostream>")
    push!(lines, "")

    push!(lines, "int main(int argc, char** argv) {")
    push!(lines, "    Verilated::commandArgs(argc, argv);")
    push!(lines, "")
    push!(lines, "    // Instantiate DUT")
    push!(lines, "    V$(module_name)* dut = new V$(module_name);")
    push!(lines, "")

    push!(lines, "    // Enable tracing")
    push!(lines, "    Verilated::traceEverOn(true);")
    push!(lines, "    VerilatedVcdC* tfp = new VerilatedVcdC;")
    push!(lines, "    dut->trace(tfp, 99);")
    push!(lines, "    tfp->open(\"$(module_name).vcd\");")
    push!(lines, "")

    push!(lines, "    // Initialize")
    push!(lines, "    dut->clk = 0;")
    push!(lines, "    dut->rst = 1;")
    push!(lines, "    dut->start = 0;")
    push!(lines, "")

    push!(lines, "    // Simulation time")
    push!(lines, "    vluint64_t sim_time = 0;")
    push!(lines, "    const vluint64_t max_time = 10000;")
    push!(lines, "")

    push!(lines, "    // Reset phase")
    push!(lines, "    for (int i = 0; i < 10; i++) {")
    push!(lines, "        dut->clk = !dut->clk;")
    push!(lines, "        dut->eval();")
    push!(lines, "        tfp->dump(sim_time++);")
    push!(lines, "    }")
    push!(lines, "    dut->rst = 0;")
    push!(lines, "")

    push!(lines, "    // Set inputs and start")
    # Set input values
    for port in rtl.ports
        if port.is_input && !(port.name in ("clk", "rst", "start"))
            push!(lines, "    dut->$(port.name) = 1;")
        end
    end
    push!(lines, "    dut->start = 1;")
    push!(lines, "")

    push!(lines, "    // Simulation loop")
    push!(lines, "    while (sim_time < max_time && !Verilated::gotFinish()) {")
    push!(lines, "        dut->clk = !dut->clk;")
    push!(lines, "        dut->eval();")
    push!(lines, "        tfp->dump(sim_time++);")
    push!(lines, "")
    push!(lines, "        // Clear start after one cycle")
    push!(lines, "        if (sim_time == 12) dut->start = 0;")
    push!(lines, "")
    push!(lines, "        // Check for done")
    push!(lines, "        if (dut->done) {")
    push!(lines, "            std::cout << \"Operation completed at time \" << sim_time << std::endl;")
    for port in rtl.ports
        if !port.is_input && port.name != "done"
            push!(lines, "            std::cout << \"$(port.name) = \" << (int)dut->$(port.name) << std::endl;")
        end
    end
    push!(lines, "            break;")
    push!(lines, "        }")
    push!(lines, "    }")
    push!(lines, "")

    push!(lines, "    // Cleanup")
    push!(lines, "    tfp->close();")
    push!(lines, "    delete dut;")
    push!(lines, "    delete tfp;")
    push!(lines, "")
    push!(lines, "    return 0;")
    push!(lines, "}")
    push!(lines, "")

    return join(lines, "\n")
end

"""
    generate_verilog(cdfg::CDFG, schedule::Schedule; options::HLSOptions=HLSOptions())

High-level function to generate complete Verilog from CDFG.
"""
function generate_verilog(cdfg::CDFG, schedule::Schedule; options::HLSOptions=HLSOptions())::String
    rtl = generate_rtl(cdfg, schedule; options=options)
    return emit_verilog(rtl)
end

# Import Dates for timestamp
import Dates
